<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreateUserSuccess ()
    {

    }

    public function testCreateUserFail ()
    {

    }

    public function testUpdateUserSuccess ()
    {

    }

    public function testUpdateUserFail ()
    {

    }

    public function testDeleteUserSuccess ()
    {

    }

    public function testDeleteUserFail ()
    {

    }

    public function testGetUsersSuccess ()
    {

    }

    public function testGetUsersFail ()
    {

    }

    public function testGetUserByIdSuccess ()
    {

    }

    public function testGetUserByIdShouldReturn404 ()
    {

    }
}
